[build-system]
requires = [
    "setuptools>=83.0.0",
    "wheel>=0.47.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "decider-ref"
version = "1.22.1"
description = ""
requires-python = ">=3.12"
authors = [
    { name = "Helmut Konrad Schewe", email = "helmutus@outlook.com" },
]
dependencies = [
    "analp>=1.0.0,<2.0.0",
    "captions>=1.0.1,<2.0.0",
    "configos>=1.0.4,<2.0.0",
    "elementae>=1.0.1,<2.0.0",
    "iamraw>=4.95.0,<5.0.0",
    "konradus>=1.0.1,<2.0.0",
    "protoerror>=3.20.2,<4.0.0",
    "texes>=1.0.1,<2.0.0",
    "upainter>=1.0.0,<2.0.0",
    "utilo>=2.110.2,<3.0.0",
    "verbo>=1.23.4,<2.0.0",
    "writers>=1.7.1,<2.0.0",
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.readme]
file = "README"
content-type = "text/markdown"

[project.optional-dependencies]
dev = [
    "callidus==1.7.1",
    "capita==1.25.3",
    "capita_ref==1.0.1",
    "codero==1.0.1",
    "decider-chapter==1.0.1",
    "figureo==1.0.1",
    "formulero==1.0.0",
    "gennex==1.1.0",
    "headnote==1.0.3",
    "hoverpower==1.7.0",
    "ibidem==1.0.2",
    "indagator==1.0.2",
    "indicibus==1.0.2",
    "jamer==1.0.2",
    "mundare==1.0.2",
    "pagenumber==1.0.0",
    "protoerror==3.20.4",
    "reftable==1.0.0",
    "tablero==1.0.1",
    "titulum==1.0.2",
    "utilotest==1.1.1",
]

[project.urls]
Homepage = "https://github.com/anaticulae/decider-ref"
Repository = "https://github.com/anaticulae/decider-ref"

[project.scripts]
decider_abbrev = "decider_abb.cli:main"
decider_abbreviation = "decider_abb.cli:main"
decider_bibliography = "decider_bib.cli:main"
decider_caption = "decider_cap.cli:main"
decider_toc = "decider_toc.cli:main"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

[tool.semantic_release.changelog]
mode = "init"
output_format = "md"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG"

[tool.semantic_release.commit_parser_options]
patch_tags = [
    "build",
    "chore",
    "ci",
    "deps",
    "docs",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = [
    "feat",
]

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "decider_abb",
    "decider_abb.features",
    "decider_bib",
    "decider_bib.features",
    "decider_cap",
    "decider_cap.features",
    "decider_ref",
    "decider_toc",
    "decider_toc.features",
]
exclude = [
    "tests*",
]

[tool.hoverpower]
packages = [
    "BACHELOR",
    "DISS",
    "DOCU",
    "MASTER",
    "ORDER",
    "TECH",
]
